In [ ]:
### welcome to numpy library 

In [2]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(5,)
1
5
int64


In [3]:
print(arr[1:4])

[20 30 40]


In [5]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b[1:,1:])

[[5 6]
 [8 9]]


In [13]:
y = np.array([12,18,25,30,15,21,1000])
y.mean()

np.float64(160.14285714285714)

In [14]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [15]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [16]:
import numpy as np 
a = np.array([[1,2,3,4,5],[1,2,3,4,5]]) 
np.save('outfile1',a)


In [17]:
import numpy as np 
b = np.load('outfile1.npy') 
print(b) 


[[1 2 3 4 5]
 [1 2 3 4 5]]


In [18]:
a = np.array([1,2,3,4,5]) 
np.savetxt('out.txt',a) 
b = np.loadtxt('out.txt') 
print(b) 


[1. 2. 3. 4. 5.]


In [19]:
import numpy as np
arr=np.arange(1,10,2) 
print("Elements of array: ",arr)
print(arr[3])
arr1=arr[np.array([4,0,2,-1,-2])]
print("Indexed Elements of array arr: ",arr1)


Elements of array:  [1 3 5 7 9]
7
Indexed Elements of array arr:  [9 1 5 9 7]


In [20]:
arr1=np.arange(4)
print("Array arr11:",arr1)
print("Element at index 0 of arri is: ", arr1[0])
print("Element at index 1 of arr1 is: ", arr1[1])


Array arr11: [0 1 2 3]
Element at index 0 of arri is:  0
Element at index 1 of arr1 is:  1


In [21]:
arr=np.arange(12)

arr1=arr.reshape(2,6)
print("Array arr1:\n",arr1)
# print("Element at eth row and eth column of arr1 is:",arr1[2,2]) 
print("Element at 1st row and 2nd column of arr1 is:", arr1[1,2])


Array arr1:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Element at 1st row and 2nd column of arr1 is: 8


In [24]:
arr2 = arr.reshape(3,2,2)
print(arr2)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [25]:
arr=np.arange(12) 
arr1=arr.reshape(2,2,3) 
print("Array arr1:\n", arr1) 
print("Element:", arr1[0,1,1])


Array arr1:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Element: 4


In [26]:
arr = np.arange(6) 
print("array arr:",arr)
print("sliced element of array: ", arr[1:5])


array arr: [0 1 2 3 4 5]
sliced element of array:  [1 2 3 4]


In [27]:
arr=np.arange(12)
arr1=arr.reshape(2,2,3)
print("Array arr1: \n",arr1)
print("\n")
print("elements of 1st row and 1st column upto last column \n", arr1[1:3,0:2,1:3])


Array arr1: 
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


elements of 1st row and 1st column upto last column 
 [[[ 7  8]
  [10 11]]]


In [28]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print('First array:') 
print(a) 
print('\n')  
   
print('Second array:') 
print(b) 
print('\n')  
   
print('First Array + Second Array' )
print( a + b)


First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [ ]:
#Python program to demonstrate
# Structured array

In [30]:
a = np.array([('Sana', 2, 21.0), ('Mansi', 7, 29.0)], 
             dtype=[('name', (np. str_, 10)), ('age', np.int32), ('weight', np.float64)])
print(type(a))


<class 'numpy.ndarray'>


In [31]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flat = arr.flatten()
print(flat)

[1 2 3 4 5 6]


In [34]:
# Create a 2 D Array
import numpy as np
arravali = np.array(np.random.randint(10,45,(3,8,2)))
print(f"The defined array is \n{arravali}")
print(f" \n The shape of the array is {arravali.shape}")

The defined array is 
[[[20 24]
  [42 13]
  [15 10]
  [23 24]
  [15 25]
  [44 14]
  [33 15]
  [34 21]]

 [[22 15]
  [20 10]
  [24 42]
  [17 18]
  [13 39]
  [39 24]
  [26 23]
  [33 29]]

 [[20 12]
  [15 38]
  [31 43]
  [38 40]
  [37 40]
  [26 14]
  [23 14]
  [31 28]]]
 
 The shape of the array is (3, 8, 2)


In [35]:
# Storing the transpose in another matrix object
nilgiri =np.transpose(arravali)
print(f" The transpose of the array is \n{nilgiri}")
print(f" \n The shape of the array is {nilgiri.shape}")


 The transpose of the array is 
[[[20 22 20]
  [42 20 15]
  [15 24 31]
  [23 17 38]
  [15 13 37]
  [44 39 26]
  [33 26 23]
  [34 33 31]]

 [[24 15 12]
  [13 10 38]
  [10 42 43]
  [24 18 40]
  [25 39 40]
  [14 24 14]
  [15 23 14]
  [21 29 28]]]
 
 The shape of the array is (2, 8, 3)


In [36]:
# Intialize a 3D array
random_3D_cohort = np.array(np.random.randint(10,45,(2,4,6)))
print(f"The defined array is \n{random_3D_cohort}")
print(f" \n The shape of the array is {random_3D_cohort.shape}")


The defined array is 
[[[30 19 25 36 23 23]
  [33 25 10 27 27 43]
  [19 35 36 15 40 33]
  [41 29 43 40 34 27]]

 [[38 10 29 40 10 21]
  [28 44 26 14 24 21]
  [14 30 33 16 19 42]
  [12 21 30 34 40 29]]]
 
 The shape of the array is (2, 4, 6)


In [38]:
# Resize the created 3D array
new_shape = (4,8,6)
resized_random_3D_cohort = np.resize(random_3D_cohort,new_shape)
print(f"The resized array is \n{resized_random_3D_cohort}")
#print(f" \n The shape of the array is {resized_random_3D_cohort.shape}")


The resized array is 
[[[30 19 25 36 23 23]
  [33 25 10 27 27 43]
  [19 35 36 15 40 33]
  [41 29 43 40 34 27]
  [38 10 29 40 10 21]
  [28 44 26 14 24 21]
  [14 30 33 16 19 42]
  [12 21 30 34 40 29]]

 [[30 19 25 36 23 23]
  [33 25 10 27 27 43]
  [19 35 36 15 40 33]
  [41 29 43 40 34 27]
  [38 10 29 40 10 21]
  [28 44 26 14 24 21]
  [14 30 33 16 19 42]
  [12 21 30 34 40 29]]

 [[30 19 25 36 23 23]
  [33 25 10 27 27 43]
  [19 35 36 15 40 33]
  [41 29 43 40 34 27]
  [38 10 29 40 10 21]
  [28 44 26 14 24 21]
  [14 30 33 16 19 42]
  [12 21 30 34 40 29]]

 [[30 19 25 36 23 23]
  [33 25 10 27 27 43]
  [19 35 36 15 40 33]
  [41 29 43 40 34 27]
  [38 10 29 40 10 21]
  [28 44 26 14 24 21]
  [14 30 33 16 19 42]
  [12 21 30 34 40 29]]]


In [43]:
resized_random_3D_cohort.flatten()

array([30, 19, 25, 36, 23, 23, 33, 25, 10, 27, 27, 43, 19, 35, 36, 15, 40,
       33, 41, 29, 43, 40, 34, 27, 38, 10, 29, 40, 10, 21, 28, 44, 26, 14,
       24, 21, 14, 30, 33, 16, 19, 42, 12, 21, 30, 34, 40, 29, 30, 19, 25,
       36, 23, 23, 33, 25, 10, 27, 27, 43, 19, 35, 36, 15, 40, 33, 41, 29,
       43, 40, 34, 27, 38, 10, 29, 40, 10, 21, 28, 44, 26, 14, 24, 21, 14,
       30, 33, 16, 19, 42, 12, 21, 30, 34, 40, 29, 30, 19, 25, 36, 23, 23,
       33, 25, 10, 27, 27, 43, 19, 35, 36, 15, 40, 33, 41, 29, 43, 40, 34,
       27, 38, 10, 29, 40, 10, 21, 28, 44, 26, 14, 24, 21, 14, 30, 33, 16,
       19, 42, 12, 21, 30, 34, 40, 29, 30, 19, 25, 36, 23, 23, 33, 25, 10,
       27, 27, 43, 19, 35, 36, 15, 40, 33, 41, 29, 43, 40, 34, 27, 38, 10,
       29, 40, 10, 21, 28, 44, 26, 14, 24, 21, 14, 30, 33, 16, 19, 42, 12,
       21, 30, 34, 40, 29], dtype=int32)

In [44]:
resized_random_3D_cohort.flatten('F')

array([30, 30, 30, 30, 33, 33, 33, 33, 19, 19, 19, 19, 41, 41, 41, 41, 38,
       38, 38, 38, 28, 28, 28, 28, 14, 14, 14, 14, 12, 12, 12, 12, 19, 19,
       19, 19, 25, 25, 25, 25, 35, 35, 35, 35, 29, 29, 29, 29, 10, 10, 10,
       10, 44, 44, 44, 44, 30, 30, 30, 30, 21, 21, 21, 21, 25, 25, 25, 25,
       10, 10, 10, 10, 36, 36, 36, 36, 43, 43, 43, 43, 29, 29, 29, 29, 26,
       26, 26, 26, 33, 33, 33, 33, 30, 30, 30, 30, 36, 36, 36, 36, 27, 27,
       27, 27, 15, 15, 15, 15, 40, 40, 40, 40, 40, 40, 40, 40, 14, 14, 14,
       14, 16, 16, 16, 16, 34, 34, 34, 34, 23, 23, 23, 23, 27, 27, 27, 27,
       40, 40, 40, 40, 34, 34, 34, 34, 10, 10, 10, 10, 24, 24, 24, 24, 19,
       19, 19, 19, 40, 40, 40, 40, 23, 23, 23, 23, 43, 43, 43, 43, 33, 33,
       33, 33, 27, 27, 27, 27, 21, 21, 21, 21, 21, 21, 21, 21, 42, 42, 42,
       42, 29, 29, 29, 29], dtype=int32)

In [45]:
a = np.random.randint(10,20,(2,3,4))    # Axis 0 - 2 ; Axis 1 - 3 ; Axis 2 - 4
print(a)
print(a.shape)


[[[19 17 12 11]
  [15 19 15 17]
  [10 13 15 18]]

 [[10 13 19 11]
  [13 13 19 19]
  [11 11 12 14]]]
(2, 3, 4)


In [46]:
np.insert(a,1,100,axis=0)

array([[[ 19,  17,  12,  11],
        [ 15,  19,  15,  17],
        [ 10,  13,  15,  18]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[ 10,  13,  19,  11],
        [ 13,  13,  19,  19],
        [ 11,  11,  12,  14]]], dtype=int32)

In [48]:
np.insert(a,1,50,axis=2)

array([[[19, 50, 17, 12, 11],
        [15, 50, 19, 15, 17],
        [10, 50, 13, 15, 18]],

       [[10, 50, 13, 19, 11],
        [13, 50, 13, 19, 19],
        [11, 50, 11, 12, 14]]], dtype=int32)

In [50]:
# Delete along Axis=0
np.delete(a,(0),axis = 0)


array([[[5, 2, 3],
        [3, 3, 5],
        [3, 3, 4]]], dtype=int32)